// Code generated by goctl-sdk. DO NOT EDIT.

import type * as types from './types';

export interface ClientOptions {
  timeout?: number;
}

export class Levee {
  private apiKey: string;
  private baseURL: string;
  private timeout: number;


  readonly llm: LlmResource;
  readonly sequences: SequencesResource;
  readonly site: SiteResource;
  readonly stats: StatsResource;
  readonly emails: EmailsResource;
  readonly contacts: ContactsResource;
  readonly funnels: FunnelsResource;
  readonly lists: ListsResource;
  readonly products: ProductsResource;
  readonly workshops: WorkshopsResource;
  readonly webhooks: WebhooksResource;
  readonly content: ContentResource;
  readonly customers: CustomersResource;
  readonly auth: AuthResource;
  readonly events: EventsResource;
  readonly offers: OffersResource;
  readonly quizzes: QuizzesResource;
  readonly tracking: TrackingResource;
  readonly orders: OrdersResource;
  readonly billing: BillingResource;

  /**
   * Create a new Levee API client.
   * @param apiKey - Your API key
   * @param baseURL - Your Levee instance URL (required - this is a self-hosted system)
   * @param options - Optional configuration
   */
  constructor(apiKey: string, baseURL: string, options: ClientOptions = {}) {
    if (!apiKey) throw new Error('API key is required');
    if (!baseURL) throw new Error('Base URL is required');
    this.apiKey = apiKey;
    this.baseURL = baseURL.replace(/\/$/, '');
    this.timeout = options.timeout ?? 30000;


    this.llm = new LlmResource(this);
    this.sequences = new SequencesResource(this);
    this.site = new SiteResource(this);
    this.stats = new StatsResource(this);
    this.emails = new EmailsResource(this);
    this.contacts = new ContactsResource(this);
    this.funnels = new FunnelsResource(this);
    this.lists = new ListsResource(this);
    this.products = new ProductsResource(this);
    this.workshops = new WorkshopsResource(this);
    this.webhooks = new WebhooksResource(this);
    this.content = new ContentResource(this);
    this.customers = new CustomersResource(this);
    this.auth = new AuthResource(this);
    this.events = new EventsResource(this);
    this.offers = new OffersResource(this);
    this.quizzes = new QuizzesResource(this);
    this.tracking = new TrackingResource(this);
    this.orders = new OrdersResource(this);
    this.billing = new BillingResource(this);
  }

  async request<T>(method: string, path: string, body?: unknown, query?: Record<string, string>): Promise<T> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeout);

    try {
      let url = `${this.baseURL}${path}`;
      if (query) {
        const params = new URLSearchParams();
        for (const [key, value] of Object.entries(query)) {
          if (value !== undefined && value !== null) {
            params.append(key, String(value));
          }
        }
        const queryString = params.toString();
        if (queryString) url += `?${queryString}`;
      }

      const response = await fetch(url, {
        method,
        headers: {
          'Authorization': `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json',
        },
        body: body ? JSON.stringify(body) : undefined,
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        const errorBody = await response.json().catch(() => ({})) as { message?: string };
        throw new Error(errorBody.message || `HTTP ${response.status}`);
      }

      if (response.status === 204) return undefined as unknown as T;
      return response.json() as Promise<T>;
    } catch (err) {
      clearTimeout(timeoutId);
      throw err;
    }
  }
}


class LlmResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async chat(request: types.LLMChatRequest): Promise<types.LLMChatResponse> {
    return this.client.request<types.LLMChatResponse>(
      'POST',
      '/sdk/v1/llm/chat',
      request
    );
  }

  /**
   * 
   */
  async config(): Promise<types.LLMConfigResponse> {
    return this.client.request<types.LLMConfigResponse>(
      'GET',
      '/sdk/v1/llm/config'
    );
  }

}


class SequencesResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async enrollInSequence(request: types.EnrollSequenceRequest): Promise<types.EnrollSequenceResponse> {
    return this.client.request<types.EnrollSequenceResponse>(
      'POST',
      '/sdk/v1/sequences/enroll',
      request
    );
  }

  /**
   * 
   */
  async getSequenceEnrollments(email: string, sequenceSlug?: string): Promise<types.ListSequenceEnrollmentsResponse> {
    const query: Record<string, string> = {};
    if (email !== undefined) query['email'] = String(email);
    if (sequenceSlug !== undefined) query['sequence_slug'] = String(sequenceSlug);
    return this.client.request<types.ListSequenceEnrollmentsResponse>(
      'GET',
      '/sdk/v1/sequences/enrollments',
      undefined,
      query
    );
  }

  /**
   * 
   */
  async pauseSequenceEnrollment(request: types.PauseSequenceRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/sequences/pause',
      request
    );
  }

  /**
   * 
   */
  async resumeSequenceEnrollment(request: types.ResumeSequenceRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/sequences/resume',
      request
    );
  }

  /**
   * 
   */
  async unenrollFromSequence(request: types.UnenrollSequenceRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/sequences/unenroll',
      request
    );
  }

}


class SiteResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async listAuthors(): Promise<types.ListSDKAuthorsResponse> {
    return this.client.request<types.ListSDKAuthorsResponse>(
      'GET',
      '/sdk/v1/site/authors'
    );
  }

  /**
   * 
   */
  async getAuthor(id: string): Promise<types.SDKAuthorInfo> {
    const path = `/sdk/v1/site/authors/${id}`;
    return this.client.request<types.SDKAuthorInfo>(
      'GET',
      path
    );
  }

  /**
   * 
   */
  async listNavigationMenus(location?: string): Promise<types.ListSDKNavigationMenusResponse> {
    const query: Record<string, string> = {};
    if (location !== undefined) query['location'] = String(location);
    return this.client.request<types.ListSDKNavigationMenusResponse>(
      'GET',
      '/sdk/v1/site/menus',
      undefined,
      query
    );
  }

  /**
   * 
   */
  async getNavigationMenu(slug: string): Promise<types.SDKNavigationMenu> {
    const path = `/sdk/v1/site/menus/${slug}`;
    return this.client.request<types.SDKNavigationMenu>(
      'GET',
      path
    );
  }

  /**
   * 
   */
  async getSiteSettings(): Promise<types.SDKSiteSettings> {
    return this.client.request<types.SDKSiteSettings>(
      'GET',
      '/sdk/v1/site/settings'
    );
  }

}


class StatsResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async getContactStats(startDate?: string, endDate?: string, groupBy?: string): Promise<types.GetContactStatsResponse> {
    const query: Record<string, string> = {};
    if (startDate !== undefined) query['start_date'] = String(startDate);
    if (endDate !== undefined) query['end_date'] = String(endDate);
    if (groupBy !== undefined) query['group_by'] = String(groupBy);
    return this.client.request<types.GetContactStatsResponse>(
      'GET',
      '/sdk/v1/stats/contacts',
      undefined,
      query
    );
  }

  /**
   * 
   */
  async getEmailStats(startDate?: string, endDate?: string, groupBy?: string): Promise<types.GetEmailStatsResponse> {
    const query: Record<string, string> = {};
    if (startDate !== undefined) query['start_date'] = String(startDate);
    if (endDate !== undefined) query['end_date'] = String(endDate);
    if (groupBy !== undefined) query['group_by'] = String(groupBy);
    return this.client.request<types.GetEmailStatsResponse>(
      'GET',
      '/sdk/v1/stats/emails',
      undefined,
      query
    );
  }

  /**
   * 
   */
  async getStatsOverview(startDate?: string, endDate?: string): Promise<types.StatsOverviewResponse> {
    const query: Record<string, string> = {};
    if (startDate !== undefined) query['start_date'] = String(startDate);
    if (endDate !== undefined) query['end_date'] = String(endDate);
    return this.client.request<types.StatsOverviewResponse>(
      'GET',
      '/sdk/v1/stats/overview',
      undefined,
      query
    );
  }

  /**
   * 
   */
  async getRevenueStats(startDate?: string, endDate?: string, groupBy?: string): Promise<types.GetRevenueStatsResponse> {
    const query: Record<string, string> = {};
    if (startDate !== undefined) query['start_date'] = String(startDate);
    if (endDate !== undefined) query['end_date'] = String(endDate);
    if (groupBy !== undefined) query['group_by'] = String(groupBy);
    return this.client.request<types.GetRevenueStatsResponse>(
      'GET',
      '/sdk/v1/stats/revenue',
      undefined,
      query
    );
  }

}


class EmailsResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async sendEmail(request: types.SendEmailRequest): Promise<types.SendEmailResponse> {
    return this.client.request<types.SendEmailResponse>(
      'POST',
      '/sdk/v1/emails/',
      request
    );
  }

  /**
   * 
   */
  async getEmailStatus(messageId: string): Promise<types.EmailStatusResponse> {
    const path = `/sdk/v1/emails/${messageId}`;
    return this.client.request<types.EmailStatusResponse>(
      'GET',
      path
    );
  }

  /**
   * 
   */
  async listEmailEvents(messageId: string): Promise<types.ListEmailEventsResponse> {
    const path = `/sdk/v1/emails/${messageId}/events`;
    return this.client.request<types.ListEmailEventsResponse>(
      'GET',
      path
    );
  }

}


class ContactsResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async createContact(request: types.ContactRequest): Promise<types.ContactResponse> {
    return this.client.request<types.ContactResponse>(
      'POST',
      '/sdk/v1/contacts',
      request
    );
  }

  /**
   * 
   */
  async getContact(id: string): Promise<types.SDKContactInfo> {
    const path = `/sdk/v1/contacts/${id}`;
    return this.client.request<types.SDKContactInfo>(
      'GET',
      path
    );
  }

  /**
   * 
   */
  async updateContact(id: string, request: types.UpdateContactRequest): Promise<types.SDKContactInfo> {
    const path = `/sdk/v1/contacts/${id}`;
    return this.client.request<types.SDKContactInfo>(
      'PUT',
      path,
      request
    );
  }

  /**
   * 
   */
  async listContactActivity(id: string, limit?: number): Promise<types.ListContactActivityResponse> {
    const path = `/sdk/v1/contacts/${id}/activity`;
    const query: Record<string, string> = {};
    if (limit !== undefined) query['limit'] = String(limit);
    return this.client.request<types.ListContactActivityResponse>(
      'GET',
      path,
      undefined,
      query
    );
  }

  /**
   * 
   */
  async addContactTags(id: string, request: types.AddContactTagsRequest): Promise<types.Response> {
    const path = `/sdk/v1/contacts/${id}/tags`;
    return this.client.request<types.Response>(
      'POST',
      path,
      request
    );
  }

  /**
   * 
   */
  async removeContactTags(id: string, request: types.RemoveContactTagsRequest): Promise<types.Response> {
    const path = `/sdk/v1/contacts/${id}/tags`;
    return this.client.request<types.Response>(
      'DELETE',
      path,
      request
    );
  }

  /**
   * 
   */
  async globalUnsubscribe(request: types.GlobalUnsubscribeRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/contacts/unsubscribe',
      request
    );
  }

}


class FunnelsResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async getFunnelStep(slug: string): Promise<types.FunnelStepInfo> {
    const path = `/sdk/v1/funnels/${slug}`;
    return this.client.request<types.FunnelStepInfo>(
      'GET',
      path
    );
  }

}


class ListsResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async subscribeToList(slug: string, request: types.SubscribeRequest): Promise<types.Response> {
    const path = `/sdk/v1/lists/${slug}/subscribe`;
    return this.client.request<types.Response>(
      'POST',
      path,
      request
    );
  }

  /**
   * 
   */
  async unsubscribeFromList(slug: string, request: types.SubscribeRequest): Promise<types.Response> {
    const path = `/sdk/v1/lists/${slug}/unsubscribe`;
    return this.client.request<types.Response>(
      'POST',
      path,
      request
    );
  }

}


class ProductsResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async getProduct(slug: string): Promise<types.BillingProductInfo> {
    const path = `/sdk/v1/products/${slug}`;
    return this.client.request<types.BillingProductInfo>(
      'GET',
      path
    );
  }

}


class WorkshopsResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async getWorkshop(slug: string): Promise<types.WorkshopEventInfo> {
    const path = `/sdk/v1/workshops/${slug}`;
    return this.client.request<types.WorkshopEventInfo>(
      'GET',
      path
    );
  }

  /**
   * 
   */
  async getWorkshopByProduct(productSlug: string): Promise<types.WorkshopEventInfo> {
    const path = `/sdk/v1/workshops/product/${productSlug}`;
    return this.client.request<types.WorkshopEventInfo>(
      'GET',
      path
    );
  }

}


class WebhooksResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async registerWebhook(request: types.RegisterWebhookRequest): Promise<types.RegisterWebhookResponse> {
    return this.client.request<types.RegisterWebhookResponse>(
      'POST',
      '/sdk/v1/webhooks/',
      request
    );
  }

  /**
   * 
   */
  async listWebhooks(): Promise<types.ListWebhooksResponse> {
    return this.client.request<types.ListWebhooksResponse>(
      'GET',
      '/sdk/v1/webhooks/'
    );
  }

  /**
   * 
   */
  async getWebhook(id: string): Promise<types.WebhookInfo> {
    const path = `/sdk/v1/webhooks/${id}`;
    return this.client.request<types.WebhookInfo>(
      'GET',
      path
    );
  }

  /**
   * 
   */
  async updateWebhook(id: string, request: types.UpdateWebhookRequest): Promise<types.WebhookInfo> {
    const path = `/sdk/v1/webhooks/${id}`;
    return this.client.request<types.WebhookInfo>(
      'PUT',
      path,
      request
    );
  }

  /**
   * 
   */
  async deleteWebhook(id: string): Promise<types.Response> {
    const path = `/sdk/v1/webhooks/${id}`;
    return this.client.request<types.Response>(
      'DELETE',
      path
    );
  }

  /**
   * 
   */
  async listWebhookLogs(id: string, limit?: number): Promise<types.ListWebhookLogsResponse> {
    const path = `/sdk/v1/webhooks/${id}/logs`;
    const query: Record<string, string> = {};
    if (limit !== undefined) query['limit'] = String(limit);
    return this.client.request<types.ListWebhookLogsResponse>(
      'GET',
      path,
      undefined,
      query
    );
  }

  /**
   * 
   */
  async testWebhook(id: string): Promise<types.TestWebhookResponse> {
    const path = `/sdk/v1/webhooks/${id}/test`;
    return this.client.request<types.TestWebhookResponse>(
      'POST',
      path
    );
  }

}


class ContentResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async listContentCategories(): Promise<types.ListSDKContentCategoriesResponse> {
    return this.client.request<types.ListSDKContentCategoriesResponse>(
      'GET',
      '/sdk/v1/content/categories'
    );
  }

  /**
   * 
   */
  async listContentPages(page?: number, pageSize?: number): Promise<types.ListSDKContentPagesResponse> {
    const query: Record<string, string> = {};
    if (page !== undefined) query['page'] = String(page);
    if (pageSize !== undefined) query['page_size'] = String(pageSize);
    return this.client.request<types.ListSDKContentPagesResponse>(
      'GET',
      '/sdk/v1/content/pages',
      undefined,
      query
    );
  }

  /**
   * 
   */
  async getContentPage(slug: string): Promise<types.SDKContentPageInfo> {
    const path = `/sdk/v1/content/pages/${slug}`;
    return this.client.request<types.SDKContentPageInfo>(
      'GET',
      path
    );
  }

  /**
   * 
   */
  async listContentPosts(page?: number, pageSize?: number, categorySlug?: string): Promise<types.ListSDKContentPostsResponse> {
    const query: Record<string, string> = {};
    if (page !== undefined) query['page'] = String(page);
    if (pageSize !== undefined) query['page_size'] = String(pageSize);
    if (categorySlug !== undefined) query['category'] = String(categorySlug);
    return this.client.request<types.ListSDKContentPostsResponse>(
      'GET',
      '/sdk/v1/content/posts',
      undefined,
      query
    );
  }

  /**
   * 
   */
  async getContentPost(slug: string): Promise<types.SDKContentPostInfo> {
    const path = `/sdk/v1/content/posts/${slug}`;
    return this.client.request<types.SDKContentPostInfo>(
      'GET',
      path
    );
  }

}


class CustomersResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async getCustomerByEmail(email: string): Promise<types.SDKCustomerInfo> {
    const path = `/sdk/v1/customers/${email}`;
    return this.client.request<types.SDKCustomerInfo>(
      'GET',
      path
    );
  }

  /**
   * 
   */
  async listCustomerInvoices(email: string, limit?: number): Promise<types.ListCustomerInvoicesResponse> {
    const path = `/sdk/v1/customers/${email}/invoices`;
    const query: Record<string, string> = {};
    if (limit !== undefined) query['limit'] = String(limit);
    return this.client.request<types.ListCustomerInvoicesResponse>(
      'GET',
      path,
      undefined,
      query
    );
  }

  /**
   * 
   */
  async listCustomerOrders(email: string, limit?: number): Promise<types.ListCustomerOrdersResponse> {
    const path = `/sdk/v1/customers/${email}/orders`;
    const query: Record<string, string> = {};
    if (limit !== undefined) query['limit'] = String(limit);
    return this.client.request<types.ListCustomerOrdersResponse>(
      'GET',
      path,
      undefined,
      query
    );
  }

  /**
   * 
   */
  async listCustomerPayments(email: string, limit?: number): Promise<types.ListCustomerPaymentsResponse> {
    const path = `/sdk/v1/customers/${email}/payments`;
    const query: Record<string, string> = {};
    if (limit !== undefined) query['limit'] = String(limit);
    return this.client.request<types.ListCustomerPaymentsResponse>(
      'GET',
      path,
      undefined,
      query
    );
  }

  /**
   * 
   */
  async listCustomerSubscriptions(email: string): Promise<types.ListCustomerSubscriptionsResponse> {
    const path = `/sdk/v1/customers/${email}/subscriptions`;
    return this.client.request<types.ListCustomerSubscriptionsResponse>(
      'GET',
      path
    );
  }

  /**
   * 
   */
  async getCustomerById(id: string): Promise<types.SDKCustomerInfo> {
    const path = `/sdk/v1/customers/id/${id}`;
    return this.client.request<types.SDKCustomerInfo>(
      'GET',
      path
    );
  }

  /**
   * 
   */
  async updateCustomer(id: string, request: types.SDKUpdateCustomerRequest): Promise<types.SDKCustomerInfo> {
    const path = `/sdk/v1/customers/id/${id}`;
    return this.client.request<types.SDKCustomerInfo>(
      'PUT',
      path,
      request
    );
  }

  /**
   * 
   */
  async deleteCustomer(id: string): Promise<types.Response> {
    const path = `/sdk/v1/customers/id/${id}`;
    return this.client.request<types.Response>(
      'DELETE',
      path
    );
  }

  /**
   * 
   */
  async listCustomerInvoicesById(id: string, limit?: number): Promise<types.ListCustomerInvoicesResponse> {
    const path = `/sdk/v1/customers/id/${id}/invoices`;
    const query: Record<string, string> = {};
    if (limit !== undefined) query['limit'] = String(limit);
    return this.client.request<types.ListCustomerInvoicesResponse>(
      'GET',
      path,
      undefined,
      query
    );
  }

  /**
   * 
   */
  async listCustomerOrdersById(id: string, limit?: number): Promise<types.ListCustomerOrdersResponse> {
    const path = `/sdk/v1/customers/id/${id}/orders`;
    const query: Record<string, string> = {};
    if (limit !== undefined) query['limit'] = String(limit);
    return this.client.request<types.ListCustomerOrdersResponse>(
      'GET',
      path,
      undefined,
      query
    );
  }

  /**
   * 
   */
  async listCustomerPaymentsById(id: string, limit?: number): Promise<types.ListCustomerPaymentsResponse> {
    const path = `/sdk/v1/customers/id/${id}/payments`;
    const query: Record<string, string> = {};
    if (limit !== undefined) query['limit'] = String(limit);
    return this.client.request<types.ListCustomerPaymentsResponse>(
      'GET',
      path,
      undefined,
      query
    );
  }

  /**
   * 
   */
  async listCustomerSubscriptionsById(id: string): Promise<types.ListCustomerSubscriptionsResponse> {
    const path = `/sdk/v1/customers/id/${id}/subscriptions`;
    return this.client.request<types.ListCustomerSubscriptionsResponse>(
      'GET',
      path
    );
  }

}


class AuthResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async changePassword(request: types.SDKChangePasswordRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/auth/change-password',
      request
    );
  }

  /**
   * 
   */
  async forgotPassword(request: types.SDKForgotPasswordRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/auth/forgot-password',
      request
    );
  }

  /**
   * 
   */
  async login(request: types.SDKLoginRequest): Promise<types.SDKAuthResponse> {
    return this.client.request<types.SDKAuthResponse>(
      'POST',
      '/sdk/v1/auth/login',
      request
    );
  }

  /**
   * 
   */
  async refreshToken(request: types.SDKRefreshTokenRequest): Promise<types.SDKAuthResponse> {
    return this.client.request<types.SDKAuthResponse>(
      'POST',
      '/sdk/v1/auth/refresh',
      request
    );
  }

  /**
   * 
   */
  async register(request: types.SDKRegisterRequest): Promise<types.SDKAuthResponse> {
    return this.client.request<types.SDKAuthResponse>(
      'POST',
      '/sdk/v1/auth/register',
      request
    );
  }

  /**
   * 
   */
  async resetPassword(request: types.SDKResetPasswordRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/auth/reset-password',
      request
    );
  }

  /**
   * 
   */
  async verifyEmail(request: types.SDKVerifyEmailRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/auth/verify-email',
      request
    );
  }

}


class EventsResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async trackEvent(request: types.EventRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/events',
      request
    );
  }

}


class OffersResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async processOffer(request: types.OfferRequest): Promise<types.OfferResponse> {
    return this.client.request<types.OfferResponse>(
      'POST',
      '/sdk/v1/offers',
      request
    );
  }

}


class QuizzesResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async getQuiz(slug: string): Promise<types.QuizInfo> {
    const path = `/sdk/v1/quizzes/${slug}`;
    return this.client.request<types.QuizInfo>(
      'GET',
      path
    );
  }

  /**
   * 
   */
  async submitQuiz(slug: string, request: types.QuizSubmitRequest): Promise<types.QuizSubmitResponse> {
    const path = `/sdk/v1/quizzes/${slug}/submit`;
    return this.client.request<types.QuizSubmitResponse>(
      'POST',
      path,
      request
    );
  }

}


class TrackingResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async trackClick(request: types.TrackClickRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/tracking/click',
      request
    );
  }

  /**
   * 
   */
  async trackConfirm(request: types.TrackConfirmRequest): Promise<types.TrackConfirmResponse> {
    return this.client.request<types.TrackConfirmResponse>(
      'POST',
      '/sdk/v1/tracking/confirm',
      request
    );
  }

  /**
   * 
   */
  async trackOpen(request: types.TrackOpenRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/tracking/open',
      request
    );
  }

  /**
   * 
   */
  async trackUnsubscribe(request: types.TrackUnsubscribeRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/tracking/unsubscribe',
      request
    );
  }

}


class OrdersResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async createOrder(request: types.OrderRequest): Promise<types.OrderResponse> {
    return this.client.request<types.OrderResponse>(
      'POST',
      '/sdk/v1/orders',
      request
    );
  }

}


class BillingResource {
  constructor(private client: Levee) {}


  /**
   * 
   */
  async createCheckoutSession(request: types.CheckoutRequest): Promise<types.CheckoutResponse> {
    return this.client.request<types.CheckoutResponse>(
      'POST',
      '/sdk/v1/billing/checkout',
      request
    );
  }

  /**
   * 
   */
  async createCustomer(request: types.CustomerRequest): Promise<types.CustomerResponse> {
    return this.client.request<types.CustomerResponse>(
      'POST',
      '/sdk/v1/billing/customers',
      request
    );
  }

  /**
   * 
   */
  async getCustomerPortal(request: types.PortalRequest): Promise<types.PortalResponse> {
    return this.client.request<types.PortalResponse>(
      'POST',
      '/sdk/v1/billing/portal',
      request
    );
  }

  /**
   * 
   */
  async createSubscription(request: types.SubscriptionRequest): Promise<types.SubscriptionResponse> {
    return this.client.request<types.SubscriptionResponse>(
      'POST',
      '/sdk/v1/billing/subscriptions',
      request
    );
  }

  /**
   * 
   */
  async cancelSubscription(id: string): Promise<types.Response> {
    const path = `/sdk/v1/billing/subscriptions/${id}/cancel`;
    return this.client.request<types.Response>(
      'POST',
      path
    );
  }

  /**
   * 
   */
  async recordUsage(request: types.UsageRequest): Promise<types.Response> {
    return this.client.request<types.Response>(
      'POST',
      '/sdk/v1/billing/usage',
      request
    );
  }

}

